name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - .github/workflows/draw.yml
      - keymap_drawer.config.yaml
      - keymap-drawer/*.yaml

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install keymap-drawer
          pip install PyYAML
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Parse keymap with virtual Combos layer
        run: |
          keymap -c "keymap_drawer.config.yaml" parse -z "config/eyelash_corne.keymap" --virtual-layers Combos > "keymap-drawer/eyelash_corne.yaml"
          yq -i '.combos[].l = ["Combos"]' "keymap-drawer/eyelash_corne.yaml"
          keymap -c "keymap_drawer.config.yaml" draw "keymap-drawer/eyelash_corne.yaml" -l "config/eyelash_corne.json" > "keymap-drawer/eyelash_corne.svg"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Draw] ${{ github.event.head_commit.message }}"
          file_pattern: keymap-drawer/*
