name: Draw Combo Only

on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - "keymap-drawer/**"
      - ".github/workflows/draw.yml"
      - "keymap_drawer.config.yaml"

jobs:
  draw-combo-only:
    # 或者 self-hosted / container
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 允许提交到仓库

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # 你也可以使用 caksoylar/keymap-drawer 提供的 install Action，或者在这里自己安装
      # 下面做一个示例，假设你想自己手动安装 keymap-drawer 与 yq
      - name: Install dependencies
        run: |
          pip install keymap-drawer
          sudo apt-get update
          sudo apt-get install -y yq

      # 1) 解析：生成带虚拟层 Combos 的 YAML
      - name: Parse keymap with virtual Combos
        run: |
          keymap -c keymap_drawer.config.yaml \
            parse -z config/eyelash_corne.keymap \
            --virtual-layers Combos \
            > keymap-drawer/eyelash_corne.yaml

      # 2) 用 yq 把所有 combos 都强制到 ["Combos"] 这一个 layer 上
      - name: Move all combos to Combos layer
        run: |
          yq -Yi '.combos.[].l = ["Combos"]' keymap-drawer/eyelash_corne.yaml

      # 3) 正式绘制 SVG
      - name: Draw combos only
        run: |
          keymap -c keymap_drawer.config.yaml \
            draw keymap-drawer/eyelash_corne.yaml \
            -k crkbd \
            > keymap-drawer/eyelash_corne.svg

      # 4) (可选) 提交结果回仓库
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add keymap-drawer/eyelash_corne.svg
          git commit -m "chore: update combo-only diagram"
          git push