name: Draw Keymap

on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - ".github/workflows/draw.yml"
      - "keymap_drawer.config.yaml"
      - "keymap-drawer/*.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v3

      # 2. 安装 Python，方便我们用 pip 安装 keymap-drawer
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. 安装 keymap-drawer CLI
      - name: Install keymap-drawer
        run: |
          pip install --upgrade pip
          pip install keymap-drawer

      # 4. 安装 yq
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      # 5. Parse -> 修改 combos -> draw
      - name: Generate combos diagram
        run: |
          # parse：加上 --virtual-layers Combos，从 eyelash_corne.keymap 中提取出 combos
          keymap -c keymap_drawer.config.yaml parse -z config/eyelash_corne.keymap --virtual-layers Combos \
            > keymap-drawer/eyelash_corne_temp.yaml

          # 用 yq 修改 combos，统一设置它们都在combos.[].l = ["Combos"]' keymap-drawer/eyelash_corne_temp.yaml

          # 再 draw：画出 diagram，输出到 eyelash_corne.svg
          keymap -c keymap_drawer.config.yaml draw keymap-drawer/eyelash_corne_temp.yaml \
            -k "corne" \
            > keymap-drawer/eyelash_corne.svg

      # 6. 可选：把生成的 svg commit 回去
      - name: Commit diagram
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add keymap-drawer/eyelash_corne.svg
          # 如果没有变化，这里会返回非零码，所以可以加 --allow-empty
          git commit -m "chore: update combos diagram"
          git push
